export const SEND_MOBILE_NUMBER_REQ = "SEND_MOBILE_NUMBER_REQ"
export const SEND_MOBILE_NUMBER_SUCCESS = "SEND_MOBILE_NUMBER_SUCCESS"


export const SEND_OTP_REQ = "SEND_OTP_REQ"
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS"


export const HANDLE_FAILURE = "HANDLE_FAILURE"


export const SEND_VISITOR_INFO_REQ = "SEND_VISITOR_INFO_REQ"
export const SEND_VISITOR_INFO_SUCCESS = "SEND_VISITOR_INFO_SUCCESS"

export const SEND_VISIT_PURPOSE_REQ = "SEND_VISIT_PURPOSE_REQ"
export const SEND_VISIT_PURPOSE_SUCCESS = "SEND_VISIT_PURPOSE_SUCCESS"

export const SEND_PURPOSE_DETAIL_REQ = "SEND_PURPOSE_DETAIL_REQ"
export const SEND_PURPOSE_DETAIL_SUCCESS = "SEND_PURPOSE_DETAIL_SUCCESS"

export const SEND_POST_IMG_REQ = "SEND_POST_IMG_REQ"
export const SEND_POST_IMG_SUCCESS = "SEND_POST_IMG_SUCCESS"